version: '3'
services:
  cinnamon:
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - COHERE_API_KEY=
      - GRAPHRAG_LLM_MODEL=gpt-4o
      - GRAPHRAG_EMBEDDING_MODEL=text-embedding-ada-002
      - GRAPHRAG_API_KEY=
    ports:
      - '7860:7860'
    image: 'ghcr.io/cinnamon/kotaemon:latest-full'
    volumes:
      - ./app_data:/app/ktem_app_data
